CREATE TABLE TRANSACCION (
	ID_TRASACCION VARCHAR(40),
	TELEFONO VARCHAR(10),
	VALOR NUMERIC,
	USUARIO VARCHAR(10),
	CONSTRAINT PK_ID_TRASACCION PRIMARY KEY (ID_TRASACCION)
	
)

CREATE TABLE USERS (
	USERNAME VARCHAR(100),
	PASSWORD VARCHAR(100),
     CONSTRAINT PK_USERNAME PRIMARY KEY (USERNAME)
	
);
